### ISSUE TITLE
[$10] URL issue when pressing browser back button

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#258] opened 2021-11-28 10:14 UTC
**Summary:**
- URL issue when pressing browser back button

**Steps to Reproduce:**

1. Go to https://platform.topcoder.com/earn/find/challenges  
2. Click on any challenges  
3. Click any of its labels  
4. On the challenges page, click the browser back button  
5. Observe the page and the URL  

**Actual Result:**
- The page directs to "?tags[]="  

**Expected Result:**
- Should go back to where you came from which is the challenge detail page  

**Environment Details:**

***Devices(s):***
- Desktop

***Operating System and version:***
- Windows 10 Pro version 20H2 build 19042.1288

***Browser and version:***
- Chrome 95.0.4638.54
- Firefox 93.0
- Microsoft Edge 95.0.1020.30

**Screen recording or Screen snapshot:**  
![back_error](/uploads/1815228cc91da8fdadd08092fb0e1e0d/back_error.mp4)

**Comment by LieutenantRoger** [comment] 2021-11-30 13:43
Challenge https://www.topcoder.com/challenges/d3003289-8c8c-4a7b-8044-7007d1680634 has been created for this ticket.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by pauline7** [comment] 2021-11-30 16:30
@bug-bash-helper unassign

**Comment by nqviet** [comment] 2021-12-01 04:52
@bug-bash-helper assign

**Comment by LieutenantRoger** [comment] 2021-12-01 04:52
Challenge https://www.topcoder.com/challenges/d3003289-8c8c-4a7b-8044-7007d1680634 has been assigned to nqv2018.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by nqviet** [comment] 2021-12-01 07:14
@bug-bash-helper https://github.com/topcoder-platform/micro-frontends-challenges-app/pull/279 is ready for review

**Comment by nqviet** [comment] 2021-12-01 07:15
@LieutenantRoger 
I also included the fixes for responsive https://github.com/topcoder-platform/micro-frontends-challenges-app/pull/280

**Comment by LieutenantRoger** [comment] 2021-12-01 14:00
@nqviet For the URL issue, could you take a look the video ? It seems won't go to the detail page per my testing when click the back in the browser. 

https://user-images.githubusercontent.com/2875203/144247725-f161b1a7-f06d-49cb-a6ae-e277715f5121.mp4

**Comment by LieutenantRoger** [comment] 2021-12-01 14:01
> @LieutenantRoger I also included the fixes for responsive #280

Thanks for the responsive fix, let me take a look

**Comment by nqviet** [comment] 2021-12-01 14:23
> 

@LieutenantRoger 
Could you please try to re-run `npm run dev` on the challenge-apps repo? I tried but could not reproduce it.

https://user-images.githubusercontent.com/36178659/144251271-eccc3a3b-c54a-4226-bf98-8d7c05095903.mp4

.

**Comment by LieutenantRoger** [comment] 2021-12-01 16:19
Thanks @nqviet for the video, it seems working fine under `https` mode.  I think then this solution is acceptable. Our Dev and Prod envrionments are all using `https` mode. 

Thanks

**Comment by nqviet** [comment] 2021-12-01 16:46
@bug-bash-helper unassign

**Comment by LieutenantRoger** [comment] 2021-12-01 16:46
Challenge https://www.topcoder.com/challenges/d3003289-8c8c-4a7b-8044-7007d1680634 nqv2018 has been unassigned.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by codejamtc** [comment] 2021-12-02 02:06
@LieutenantRoger Not working for me on Dev

https://user-images.githubusercontent.com/42398485/144344194-8c2dfede-9faa-495a-b4e2-a3d5cf89d5e2.mp4


https://user-images.githubusercontent.com/42398485/144344201-d4c26266-147c-4979-996c-c030bbeecfb9.mp4

**Comment by codejamtc** [comment] 2021-12-02 03:27
Fixed :ok:

https://user-images.githubusercontent.com/42398485/144352535-a76786a6-645f-4a6b-a864-8aa952f3a246.mp4

**Comment by LieutenantRoger** [comment] 2021-12-03 15:20
Challenge https://www.topcoder.com/challenges/d3003289-8c8c-4a7b-8044-7007d1680634 nqv2018 has been unassigned.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by LieutenantRoger** [comment] 2021-12-03 15:20
nqv2018 has been unassigned because this ticket doesn't have the tcx_OpenForPickup label.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by LieutenantRoger** [comment] 2021-12-03 15:21
Challenge https://www.topcoder.com/challenges/d3003289-8c8c-4a7b-8044-7007d1680634 has been assigned to nqv2018.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by codejamtc** [comment] 2021-12-07 04:39
Fixed in Prod :ok:

https://user-images.githubusercontent.com/42398485/144967369-acd54fa9-3e64-477e-b569-344fc07ade09.mp4

**Comment by LieutenantRoger** [comment] 2021-12-07 04:39
Payment task has been updated: https://www.topcoder.com/challenges/d3003289-8c8c-4a7b-8044-7007d1680634
*Payments Complete*
Winner: nqv2018
Copilot: lieutenantroger
Challenge `d3003289-8c8c-4a7b-8044-7007d1680634` has been paid and closed.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Closed by codejamtc** 2021-12-07 04:39 UTC
Labels: QA Pass on Dev, QA Pass on Prod, P1, tcx_FixAccepted, tcx_Assigned, CF, Functional, Valid, FE
